---
AWSTemplateFormatVersion: "2010-09-09"


Description: >-
  EC2 instances configuration


Parameters:

  VpcId:
    Description: VpcId
    Type: String
    Default: ""

  MyIP:
    Description: My IP address to SSH the EC2 instance
    Type: String
    Default: ""

  Environment:
    Description: Environment (dev/qa/prod)
    Type: String
    Default: "dev"

  InstanceAMI:
    Description: Instance AMI (free tier elegible)
    Type: String
    Default: ""

  InstanceType:
    Description: Instance Type (select t2.micro because of the free tier)
    Type: String
    Default: "t2.micro"

  Subnet:
    Description: Subnet for your EC2 instances
    Type: String
    Default: ""

  EC2Key:
    Description: Key to access EC2 instance
    Type: String
    Default: ""

Resources:
  EC2InstanceA:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - Fn::ImportValue:
            Fn::Sub: ${Environment}-EC2-sg-A
      ImageId:
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: EC2Key
      SubnetId:
        Ref: Subnet
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${Environment}-ec2-instance-A
  EC2InstanceB:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
        - Fn::ImportValue:
            Fn::Sub: ${Environment}-EC2-sg-B
      ImageId:
        Ref: InstanceAMI
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: EC2Key
      SubnetId:
        Ref: Subnet
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${Environment}-ec2-instance-B
